version: '3'
services:
  #nginx:
  #  build: .
  #  image: nginx-iqoption
  #  container_name: nginx-iqoption
  #  # working_dir: /application
  #  volumes:
  #   - .:/var/www/html
  #  #- ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #  ports:
  #    - "8080:80"

  webapp-service:
    image: node:10-slim
    container_name: iqoption-dev
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command:
      sh -c 'npm run serve'
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API=http://localhost:8081
      - VUE_APP_NAME=DayTrade.Reviews

