apiVersion: apps/v1
kind: Deployment
metadata:
  name: iqoption-dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iqoption
      tier: frontend
  template:
    metadata:
      labels:
        app: iqoption
        tier: frontend
    spec:
      containers:
        - name: iqoption
          image: wouerner/iqoption-dashboard:latest
          ports:
            - containerPort: 80
          env:
          - name: VUE_APP_API
            value: "http://servico-ioption-nginx:8081"
          - name: VUE_APP_NAME
            value: "Score.trade"
          imagePullPolicy: Always
